### ISSUE TITLE
pkj uninstall erased my list of installed packages

### ISSUE THREAD

**Issue by cbm755** [apjanke/octave-packajoozle#58] opened 2019-04-13 04:54 UTC
This is a somewhat recent Octave 6.0.0:
```
>>> pkg list
Package Name  | Version | Installation directory
--------------+---------+-----------------------
     doctest  |   0.7.0 | /home/cbm/.local/share/octpkgs/6.0.0/doctest-0.7.0
          io  |  2.4.12 | /home/cbm/.local/share/octpkgs/6.0.0/io-2.4.12
       optim  |   1.6.0 | /home/cbm/.local/share/octpkgs/6.0.0/optim-1.6.0
 packajoozle  |   0.1.0 | /home/cbm/.local/share/octpkgs/6.0.0/packajoozle-0.1.0
  statistics  |   1.4.0 | /home/cbm/.local/share/octpkgs/6.0.0/statistics-1.4.0
      struct  |  1.0.16 | /home/cbm/.local/share/octpkgs/6.0.0/struct-1.0.16
    symbolic  |   2.7.1 | /home/cbm/.local/share/octpkgs/6.0.0/symbolic-2.7.1
```
(that's an old packajoozle from about a month ago: I think that's irrelevant).

Then I did `pkj uninstall doctest`.  (This seems to be the crucial step to reproduce)

Then I did `pkj review doctest-0.7.0.tar.gz`.

Now:
```
>>> pkg list
no packages installed.
```
All the files are still under `${HOME}/.local/share/octpkgs/6.0.0/`.

- - - -

I think this is reproducible, but I haven't tried without my custom path stuff, which is the following in my .octaverc:
```
%% I want to store my packages in version-specific dirs
tmp_pkg_path = fullfile(getenv('HOME'), '.local/share/octpkgs/', ver('octave').Version);
mkdir(tmp_pkg_path);  % oct 6 needs this?
pkg('prefix', tmp_pkg_path, tmp_pkg_path);
pkg('local_list', fullfile(tmp_pkg_path, 'octave_packages'));
clear tmp_pkg_path
```

**Comment by apjanke** [comment] 2019-04-13 07:15
I can reproduce with default Octave 6.0.0 and the current packajoozle on macOS.

It looks like the issue is that `pkj` is saving the `local_list` index file with the wrong variable name in it.

```
octave:6> pkg list
Package Name  | Version | Installation directory
--------------+---------+-----------------------
     doctest  |   0.6.1 | /Users/janke/.local/share/octpkgs/6.0.0/doctest-0.6.1
          io  |  2.4.12 | /Users/janke/.local/share/octpkgs/6.0.0/io-2.4.12
  statistics  |   1.4.1 | /Users/janke/.local/share/octpkgs/6.0.0/statistics-1.4.1
octave:7> pkg('local_list')
/Users/janke/.local/share/octpkgs/6.0.0/octave_packages
octave:8> s = load(pkg('local_list'));
octave:9> fieldnames(s)
ans =
{
  [1,1] = local_packages
}

octave:10> pkj uninstall doctest
pkj: uninstalling from custom: doctest 0.6.1
pkj: packages uninstalled OK
octave:11> pkg list
no packages installed.
octave:12> s = load(pkg('local_list'));
octave:13> fieldnames(s)
ans =
{
  [1,1] = octave_packages
}

octave:14>
```

I'll review the index-saving logic and see if I can find where it's going wrong here.

**Comment by apjanke** [comment] 2019-04-13 07:23
Fixed in https://github.com/apjanke/octave-packajoozle/commit/7c45c15c3792e8f11823ed4d8134be6f5f8f969b.

After:

```
octave:7> pkg list
Package Name  | Version | Installation directory
--------------+---------+-----------------------
     doctest  |   0.6.1 | /Users/janke/.local/share/octpkgs/6.0.0/doctest-0.6.1
          io  |  2.4.12 | /Users/janke/.local/share/octpkgs/6.0.0/io-2.4.12
  statistics  |   1.4.1 | /Users/janke/.local/share/octpkgs/6.0.0/statistics-1.4.1
octave:8> pkj uninstall doctest
pkj: uninstalling from custom: doctest 0.6.1
pkj: packages uninstalled OK
octave:9> pkg list
Package Name  | Version | Installation directory
--------------+---------+-----------------------
          io  |  2.4.12 | /Users/janke/.local/share/octpkgs/6.0.0/io-2.4.12
  statistics  |   1.4.1 | /Users/janke/.local/share/octpkgs/6.0.0/statistics-1.4.1
octave:10>
```

**Closed as completed by apjanke** 2019-04-13 07:23 UTC
Labels: bug
